# Generated by Django 4.2.13 on 2024-06-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0006_alter_billing_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
